"""Chunk ORM model.

Holds both the chunk metadata and its embedding vector (pgvector). In stage 1 the
pgvector-backed VectorStore reads/writes this table; if a different vector store is
introduced later, the vector column can move while the metadata stays here.
"""
from __future__ import annotations

from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.core.config import settings
from app.db.base import Base
from sqlalchemy import DateTime, func
from datetime import datetime

from app.utils.id_generator import new_chunk_id


class Chunk(Base):
    __tablename__ = "chunks"

    # chunk_id — generated by the RAG center (UUID).
    id: Mapped[str] = mapped_column(String(64), primary_key=True, default=new_chunk_id)
    tenant_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    kb_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("knowledge_bases.id", ondelete="CASCADE"), nullable=False, index=True
    )
    document_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True
    )
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    # "metadata" is reserved by SQLAlchemy Declarative, so the attribute is renamed
    # while the DB column stays "metadata".
    chunk_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        "metadata", JSONB, nullable=True
    )
    embedding: Mapped[list[float]] = mapped_column(
        Vector(settings.embedding_dim), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
