"""RetrievalLog ORM model — one row per RAG retrieve call, for observability."""
from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.utils.id_generator import new_retrieval_log_id


class RetrievalLog(Base):
    __tablename__ = "retrieval_logs"

    # retrieval_log_id — generated by the RAG center (UUID).
    id: Mapped[str] = mapped_column(String(64), primary_key=True, default=new_retrieval_log_id)
    tenant_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    kb_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # user_id — supplied by the caller; recorded for logging and future ACL filtering.
    user_id: Mapped[str | None] = mapped_column(String(128), nullable=True, index=True)
    query: Mapped[str] = mapped_column(Text, nullable=False)
    # Snapshot of returned chunks (document_id, chunk_id, title, score, ...).
    retrieved_chunks: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB, nullable=True)
    top_k: Mapped[int] = mapped_column(Integer, nullable=False)
    vector_store: Mapped[str] = mapped_column(String(64), nullable=False)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
